---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

provisioner:
  name: ansible

verifier:
  name: ansible
