---
dependency:
  name: galaxy

driver:
  name: delegated

platforms: []
  # - name: instance
  #   image: quay.io/centos/centos:stream8
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

provisioner:
  name: ansible
  inventory:
    hosts:
      link: inventory.yml

verifier:
  name: ansible
