---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: recipe-mysql
  labels:
    app: recipe
    tier: bdd
spec:
  serviceName: recipe-mysql
  replicas: 1
  selector:
    matchLabels:
      app: recipe
      tier: bdd
  template:
    metadata:
      labels:
        app: recipe
        tier: bdd
    spec:
      containers:
      - name: recipe-mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-db
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret-db
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-db
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi