---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-db
  labels:
    app: recipe
    tier: secret-bdd
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=        # "rootpass" en base64
  MYSQL_USER: cmVjaXBlcl91c2Vy               # "recipe_user" en base64
  MYSQL_PASSWORD: cmVjaXBlcGFzcw==           # "recipepass" en base64