apiVersion: v1
kind: Service
metadata:
  name: recipe-app
  labels:
    app: recipe
    tier: svc-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    tier: frontend
