version: '3.8'

services:
  recipe-api:
    image: api:latest
    container_name: recipe_api
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://recipe_db:3306/recipe-demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=recipe_user
      - SPRING_APPLICATION_NAME=recipe-demo
      - FRONTEND_URL=http://your_public_ip:5173
      - SPRING_DATASOURCE_PASSWORD=recipe_pass
    depends_on:
      recipe-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - recipe-net

  recipe-db:
    image: mysql:8.0
    container_name: recipe_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=recipe-demo
      - MYSQL_USER=recipe_user
      - MYSQL_PASSWORD=recipe_pass
    volumes:
      - recipe_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "recipe_user", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - recipe-net

  recipe-frontend:
    image: frontend:latest
    container_name: recipe_frontend
    ports:
      - "5173:80"
    environment:
      - API_URL=https://your_public_ip:8443/api
    depends_on:
      - recipe-api
    restart: unless-stopped
    networks:
      - recipe-net

volumes:
  recipe_db_data:
    name: recipe_db_data
networks:
  recipe-net:
    driver: bridge
    name: recipe-net
