apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recipe-ns  # Namespace à utiliser pour toutes les ressources

resources:
  - ns        # Contient la définition du namespace
  - storageclass
  - database
  - front
  - phpmyadmin
  # - nginx-and-metallb