apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-frontend
  labels:
    app: recipe
spec:
  selector:
    matchLabels:
      app: recipe
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: recipe
        tier: frontend
    spec:
      containers:
      #- image: olivierkkoc/recipe-frontend:demo
      - image: blondel/frontend:v1
        name: recipe-app
        env:
        - name: API_URL
          value: https://54.152.219.126:30443
        ports:
        - containerPort: 80
          name: app-port
