apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe
  labels:
    app: recipe
spec:
  selector:
    matchLabels:
      app: recipe
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recipe
        tier: frontend
    spec:
      containers:
      - image: olivierkkoc/recipe-frontend:demo
        name: recipe-app
        env:
        - name: API_URL
          value: http://recipe-api:5173
        ports:
        - containerPort: 80
          name: app-port