apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany        # NFS supporte plusieurs accès en lecture/écriture
  storageClassName: example-nfs
  resources:
    requests:
      storage: 5Gi
