---
# tasks file for docker-installation

- name: Mettre à jour le cache APT
  ansible.builtin.apt:
    update_cache: yes

- name: Installer les dépendances requises pour Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Créer le répertoire /etc/apt/keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Télécharger la clé GPG de Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

- name: Récupérer l'architecture du système
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Charger les informations de la distribution (os-release)
  ansible.builtin.slurp:
    src: /etc/os-release
  register: os_release_raw

- name: Extraire le nom de code Ubuntu
  ansible.builtin.set_fact:
    ubuntu_codename: "{{ (os_release_raw['content'] | b64decode).split('\n') | select('match', '^UBUNTU_CODENAME=|^VERSION_CODENAME=') | map('regex_replace', '^.*?=', '') | list | first }}"

- name: Ajouter le dépôt Docker officiel
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable
    mode: '0644'

- name: Mettre à jour le cache APT après ajout du dépôt Docker
  ansible.builtin.apt:
    update_cache: yes

- name: Installer Docker & plugins
  ansible.builtin.apt:
    name:
      - "docker-ce={{ docker_version }}"
      - "docker-ce-cli={{ docker_version }}"
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  

- name: S'assurer que le service Docker est démarré et activé
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

