---
# tasks file for build-image

- name: Exécuter un script dans le répertoire parent
  command: pwd
  args:
    chdir: "../recipe-api"

- name: Build image API
  docker_image:
    name: "api:{{ tag_api }}"
    build:
      path: "{{ api_src_path }}"
    source: build  

- name: Build image Frontend
  docker_image:
    name: "frontend:{{ tag_front }}"
    build:
      path: "{{ frontend_src_path }}"
    source: build  