
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-backend
  labels:
    app: recipe
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: recipe
        tier: backend
    spec:
      containers:
      - name: recipe-api
        image: blondel/api:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: recipe-backend-config
              key: SPRING_DATASOURCE_URL
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: recipe-backend-config
              key: FRONTEND_URL
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: recipe-backend-config
              key: SPRING_APPLICATION_NAME
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
      restartPolicy: Always
