---
# tasks file for deployment

- name: Templatiser le fichier docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_project_dir }}/docker-compose.yml"
    mode: '0644'

- name: Lancer les conteneurs via Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ compose_project_dir }}"
    state: present
  register: compose_result

