---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local

    staging:
      ansible_host: 13.218.63.50
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ansible.pem

    prod:
      ansible_host: 13.221.238.147
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ansible.pem
