---
# tasks file for deployment

- name: Templatiser le fichier docker-compose.yml
  template:
    src: docker-compose.fullstack.yml.j2
    dest: ../docker-compose.fullstack.yml
    mode: '0644'

- name: pwd
  command: sh -c "pwd"

- name: Lancer le docker-compose
  command: sh -c "docker compose -f ../docker-compose.fullstack.yml up -d"
