---
# tasks file for deployment

- name: Générer le fichier docker-compose.yml depuis un template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_file_path }}"
    mode: '0644'


- name: Lancer les conteneurs via Docker Compose
  community.docker.docker_compose:
    project_src: "{{ compose_project_dir }}"
    files:
      - "{{ compose_file_path }}"
    state: present
    restarted: true
  register: compose_result

- name: Afficher les services démarrés
  ansible.builtin.debug:
    var: compose_result
