name: Build k3s Image
on:
  workflow_run:
    workflows: ["Build Base Image"]
    types: [completed]
    branches: [hashicorp]

jobs:
  build-k3s:  
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      image-id: ${{ steps.build.outputs.image-id }}
      image-name: ${{ steps.build.outputs.image-name }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"
      
      - name: Build k3s Image
        id: build
        run: |
          cd packer/k3s_image
          packer init .
          packer build .
          
          if [ ! -f manifest.json ]; then
            echo "❌ Manifest not found"
            exit 1
          fi
          
          IMAGE_ID=$(jq -r '.builds[0].custom_data.image_id // .builds[0].artifact_id // "unknown"' manifest.json)
          IMAGE_NAME=$(jq -r '.builds[0].custom_data.image_name // "k3s-image"' manifest.json)
          
          echo "image-id=$IMAGE_ID" >> $GITHUB_OUTPUT
          echo "image-name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          
          echo "✅ Built k3s image: $IMAGE_NAME (ID: $IMAGE_ID)"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
      
      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: k3s-image-manifest  
          path: packer/k3s_image/manifest.json  
          retention-days: 1